[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["duck_db_mcp"]

[project]
name = "duck-db-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "duckdb>=1.5.5",
    "fastmcp>=3.4.4",
    "mcp[cli]>=1.28.1",
    "pandas>=3.0.5",
    "tabulate>=0.10.0",
]

[project.scripts]
duck_mcp = "duck_db_mcp:main"

